### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by TheHolyRoger** [Qolzam/telar-cli#3]
These binaries distribute a backdoor that is currently undetected.

**Comment by Qolzam** [comment]
Thanks for feedback @TheHolyRoger  , Could you please give me more details?

**Comment by Qolzam** [comment]
Dear @TheHolyRoger , I am going to close this issue as there is no evidence/reproducing example.  Please feel free to reopen the issue if you feel the issue exit.
Thanks !
