### ISSUE TITLE
Failure to deploy telar-web

### ISSUE THREAD

**Issue by ChrisCastr0** [Qolzam/telar-cli#5]
After filling out the form and clicking deploy the program crashes when it tries to initialize telar social giving me an error message that says I used an "Invalid Auth Method"

![image](https://user-images.githubusercontent.com/70775232/93153561-61972e80-f6b6-11ea-8b5e-bbdee080a498.png)

![image](https://user-images.githubusercontent.com/70775232/93153441-1a10a280-f6b6-11ea-9dfb-32131f724709.png)

I am running on Ubuntu 20.04

Note: A member of my team (who is using a Mac) and myself are sharing resources (i.e. firebase bucket, mongodb, recaptcha, etc) and he did not experience these problems.

**Comment by Qolzam** [comment]
Hi @ChrisCastr0 , I could not reproduce this issue. However the error should come from git push. Did you configure [SSH for you Github](https://github.com/Qolzam/telar-cli/blob/master/docs/ofcc-setup/2.md#3-adding-ssh-key-to-github) ?

**Comment by ChrisCastr0** [comment]
@Qolzam  I did configure the ssh for github.

![image](https://user-images.githubusercontent.com/70775232/93284296-2f093680-f787-11ea-84c7-00142f93eee3.png)

It is set on my local machine and I also added the key to my github account.

**Comment by Qolzam** [comment]
OFC deprecated and new update is working with OpenFaaS #7
